INSERT IGNORE INTO `tumaker_query_template` (`id`, `template`, `template_parameter`, `template_name`, `template_type`, `template_desc`, `language_type`, `template_query_type`, `query_source`) VALUES (1, 'CALL osgraph.get_repo_contribution(\'{"repo_id":${{repo_id}},"start_timestamp":${{start_timestamp}},"end_timestamp":${{end_timestamp}},"top_n":${{top_n}}}\') YIELD start_node, relationship, end_node return start_node, relationship, end_node', '[{"parameterName":"repo_id","parameterValue":"","valueType":"LONG"},{"parameterName":"start_timestamp","parameterValue":"","valueType":"LONG"},{"parameterName":"end_timestamp","parameterValue":"","valueType":"LONG"},{"parameterName":"top_n","parameterValue":"10","valueType":"LONG"}]', '项目贡献', 'REPO_CONTRIBUTE', '', 'CYPHER', 'FUNCTION', 'github_repo');
INSERT IGNORE INTO `tumaker_query_template` (`id`, `template`, `template_parameter`, `template_name`, `template_type`, `template_desc`, `language_type`, `template_query_type`, `query_source`) VALUES (2, 'CALL osgraph.get_repo_by_repo(\'{"repo_id":${{repo_id}}, "top_n":${{top_n}}}\') YIELD start_node, relationship, end_node return start_node, relationship, end_node', '[{"parameterName":"repo_id","parameterValue":"","valueType":"LONG"},{"parameterName":"top_n","parameterValue":"10","valueType":"LONG"}]', '项目生态', 'REPO_ECOLOGY', '', 'CYPHER', 'FUNCTION', 'github_repo');
INSERT IGNORE INTO `tumaker_query_template` (`id`, `template`, `template_parameter`, `template_name`, `template_type`, `template_desc`, `language_type`, `template_query_type`, `query_source`) VALUES (3, 'CALL osgraph.get_repo_developers_profile(\'{"repo_id":${{repo_id}},"company_topn":${{company_topn}},"country_topn":${{country_topn}},"developer_topn":${{developer_topn}}}\') YIELD start_node, relationship, end_node return start_node, relationship, end_node', '[{"parameterName":"repo_id","parameterValue":"","valueType":"LONG"},{"parameterName":"company_topn","parameterValue":"5","valueType":"LONG"},{"parameterName":"country_topn","parameterValue":"5","valueType":"LONG"},{"parameterName":"developer_topn","parameterValue":"3","valueType":"LONG"}]', '项目社区', 'REPO_COMMUNITY', '', 'CYPHER', 'FUNCTION', 'github_repo');
INSERT IGNORE INTO `tumaker_query_template` (`id`, `template`, `template_parameter`, `template_name`, `template_type`, `template_desc`, `language_type`, `template_query_type`, `query_source`) VALUES (4, 'CALL osgraph.get_developer_contribution(\'{"developer_id":${{developer_id}},"top_n":${{top_n}}}\') YIELD start_node, relationship, end_node return start_node, relationship, end_node', '[{"parameterName":"developer_id","parameterValue":"","valueType":"LONG"},{"parameterName":"top_n","parameterValue":"10","valueType":"LONG"}]', '开发活动', 'ACCT_ACTIVITY', '', 'CYPHER', 'FUNCTION', 'github_user');
INSERT IGNORE INTO `tumaker_query_template` (`id`, `template`, `template_parameter`, `template_name`, `template_type`, `template_desc`, `language_type`, `template_query_type`, `query_source`) VALUES (5, 'CALL osgraph.get_developer_by_developer(\'{"developer_id":${{developer_id}},"top_n":${{top_n}}}\') YIELD start_node, relationship, end_node return start_node, relationship, end_node', '[{"parameterName":"developer_id","parameterValue":"","valueType":"LONG"},{"parameterName":"top_n","parameterValue":"10","valueType":"LONG"}]', '开源伙伴', 'ACCT_PARTNER', '', 'CYPHER', 'FUNCTION', 'github_user');
INSERT IGNORE INTO `tumaker_query_template` (`id`, `template`, `template_parameter`, `template_name`, `template_type`, `template_desc`, `language_type`, `template_query_type`, `query_source`) VALUES (6, 'CALL osgraph.get_developer_repos_profile(\'{"developer_id":${{developer_id}},"topic_topn":${{topic_topn}},"repo_topn":${{repo_topn}}}\') YIELD start_node, relationship, end_node return start_node, relationship, end_node', '[{"parameterName":"developer_id","parameterValue":"","valueType":"LONG"},{"parameterName":"topic_topn","parameterValue":"5","valueType":"LONG"},{"parameterName":"repo_topn","parameterValue":"3","valueType":"LONG"}]', '开源兴趣', 'ACCT_INTEREST', '', 'CYPHER', 'FUNCTION', 'github_user');



