FROM acs-reg.alipay.com/antstack/sofaboot-dragonwell8-onbuild:2210.6_aarch64 AS BUILDER

# build with java8
#ENV JAVA_HOME $JAVA_8_HOME
#ENV PATH $JAVA_HOME/bin:$PATH

# using build mode: release
ENV build_mode release
#RUN cp /opt/taobao/install/maven/settings-${build_mode}.xml /root/.m2/settings.xml

# build package
RUN bash build.sh tumaker . /home/admin/release

### image for running

FROM  acs-reg.alipay.com/antstack/sofaboot-dragonwell8-anolisos:2210.6_aarch64

WORKDIR /home/admin

# copy app package from builder image
COPY --from=BUILDER /home/admin/release/target.tar.gz /home/admin/release/run/

# 获取前端资源
#ARG YUYAN_STATIC_ASSETS_URL

#RUN curl -LS $YUYAN_STATIC_ASSETS_URL > static-assets.tgz && tar xzvf static-assets.tgz

# add entrypoint
#COPY dependent  /dependent
COPY conf /conf
COPY biz/database/tumaker /conf/db/tumaker

USER root

#RUN bash /dependent/build.sh
RUN bash /conf/bin/build.sh

RUN chown -R admin.admin /home/admin

#CMD /bin/bash -c "sleep inf"
#CMD []
ENTRYPOINT ["/bin/bash", "/conf/startup.sh"]
