name: Deploy-Prod

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to deploy"
        required: true
        default: "release"
        type: string

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and execute deployment script
        env:
          PROD_HOST: ${{ secrets.PROD_HOST }}
          PROD_USER: ${{ secrets.PROD_USER }}
          PROD_PWD: ${{ secrets.PROD_PWD }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          sshpass -p "$PROD_PWD" ssh -o StrictHostKeyChecking=no $PROD_USER@$PROD_HOST << EOF
          set -e
          export PATH="/root/miniconda3/bin:\$PATH"
          source /root/miniconda3/etc/profile.d/conda.sh
          conda activate osgraph-env
          cd $DEPLOY_PATH
          git checkout release
          git pull
          bash ./bin/build.sh
          bash ./bin/start.sh prod
          EOF
