name: Deploy-Pre

on:
  push:
    branches:
      - master

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and execute deployment script
        env:
          PRE_HOST: ${{ secrets.PRE_HOST }}
          PRE_USER: ${{ secrets.PRE_USER }}
          PRE_PWD: ${{ secrets.PRE_PWD }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          sshpass -p "$PRE_PWD" ssh -o StrictHostKeyChecking=no $PRE_USER@$PRE_HOST << EOF
          set -e
          cd $DEPLOY_PATH
          git checkout master
          git pull
          source /root/.bashrc
          conda init
          conda activate osgraph-env
          bash ./bin/build.sh
          bash ./bin/start.sh prod
          EOF
