name: Test SSH Connection

on:
  workflow_dispatch: # 手动触发 Workflow

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH and Poetry
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER << EOF
          set -e
          echo "Testing SSH connection..."
          echo "Current PATH: \$PATH"
          echo "Checking Poetry version..."
          poetry --version || echo "Poetry not found"
          EOF
